namespace: compscidr
name: uncompress
version: 0.0.8
readme: README.md
authors:
  - Jason Ernst <ernstjason1@gmail.com>
description: Enables uncompress of .gz and .bz2 files which aren't tarred
license_file: LICENSE
tags:
  - tools
  - uncompress
  - gz
  - bz2
dependencies: {}
repository: https://github.com/compscidr/ansible-uncompress
documentation: https://github.com/compscidr/ansible-uncompress/README.md
homepage: https://github.com/compscidr/ansible-uncompress
issues: https://github.com/compscidr/ansible-uncompress/issues
build_ignore: []
