---
- name: Converge
  hosts: all
  tasks:
    - name: Install required packages for testing
      ansible.builtin.package:
        name:
          - gzip
          - bzip2
          - xz-utils
          - file
        state: present
      become: true

    - name: Create test directory
      ansible.builtin.file:
        path: /tmp/uncompress_test
        state: directory
        mode: '0755'

    - name: Create test files for compression
      ansible.builtin.copy:
        content: |
          This is a test file for {{ item }} compression.
          It contains multiple lines to test the uncompress functionality.
          This should be properly uncompressed by the module.
        dest: /tmp/uncompress_test/test_{{ item }}.txt
        mode: '0644'
      loop:
        - gzip
        - bzip2
        - xz

    - name: Check if compressed files exist
      ansible.builtin.stat:
        path: /tmp/uncompress_test/test.{{ item }}
      register: compressed_files
      loop:
        - gz
        - bz2
        - xz

    - name: Compress test files with gzip
      ansible.builtin.shell: gzip -c /tmp/uncompress_test/test_gzip.txt > /tmp/uncompress_test/test.gz
      when: not (compressed_files.results[0].stat.exists | default(false))
      changed_when: not (compressed_files.results[0].stat.exists | default(false))

    - name: Compress test files with bzip2
      ansible.builtin.shell: bzip2 -c /tmp/uncompress_test/test_bzip2.txt > /tmp/uncompress_test/test.bz2
      when: not (compressed_files.results[1].stat.exists | default(false))
      changed_when: not (compressed_files.results[1].stat.exists | default(false))

    - name: Compress test files with xz
      ansible.builtin.shell: xz -c /tmp/uncompress_test/test_xz.txt > /tmp/uncompress_test/test.xz
      when: not (compressed_files.results[2].stat.exists | default(false))
      changed_when: not (compressed_files.results[2].stat.exists | default(false))

    - name: Test uncompress gzip file
      compscidr.uncompress.uncompress:
        src: /tmp/uncompress_test/test.gz
        dest: /tmp/uncompress_test/uncompressed_gzip.txt
        copy: false

    - name: Test uncompress bzip2 file
      compscidr.uncompress.uncompress:
        src: /tmp/uncompress_test/test.bz2
        dest: /tmp/uncompress_test/uncompressed_bzip2.txt
        copy: false

    - name: Test uncompress xz file
      compscidr.uncompress.uncompress:
        src: /tmp/uncompress_test/test.xz
        dest: /tmp/uncompress_test/uncompressed_xz.txt
        copy: false
