---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Re-run uncompress tasks to get return values
      block:
        - name: Test uncompress with .gz file (no copy)
          compscidr.uncompress.uncompress:
            copy: false
            src: https://github.com/cheat/cheat/releases/download/4.3.1/cheat-linux-amd64.gz
            dest: /tmp/cheat
            mode: '755'
          register: result_cheat

        - name: Test uncompress with local .gz file (with copy)
          compscidr.uncompress.uncompress:
            copy: true
            src: /tmp/test.txt.gz
            dest: /tmp/test-uncompressed.txt
            mode: '644'
          register: result_gz

        - name: Test uncompress with .bz2 file
          compscidr.uncompress.uncompress:
            copy: true
            src: /tmp/test2.txt.bz2
            dest: /tmp/test2-uncompressed.txt
            mode: '644'
          register: result_bz2

        - name: Test uncompress with .gz file to directory
          compscidr.uncompress.uncompress:
            copy: true
            src: /tmp/test3.txt.gz
            dest: /tmp/uncompress-test-dir/
            mode: '644'
          register: result_gz_dir

        - name: Test uncompress with .bz2 file to directory
          compscidr.uncompress.uncompress:
            copy: true
            src: /tmp/test4.txt.bz2
            dest: /tmp/uncompress-test-dir/
            mode: '644'
          register: result_bz2_dir

        - name: Test uncompress with .tar.gz file to directory
          compscidr.uncompress.uncompress:
            copy: true
            src: /tmp/test5.tar.gz
            dest: /tmp/uncompress-test-dir/
            mode: '644'
          register: result_tar_gz_dir

    - name: Verify dest is returned correctly for cheat
      ansible.builtin.assert:
        that:
          - result_cheat.dest is defined
          - result_cheat.dest == "/tmp/cheat"
        fail_msg: "dest return value not correct for cheat"
        success_msg: "dest return value correct for cheat"

    - name: Verify dest is returned correctly for gz file
      ansible.builtin.assert:
        that:
          - result_gz.dest is defined
          - result_gz.dest == "/tmp/test-uncompressed.txt"
        fail_msg: "dest return value not correct for gz file"
        success_msg: "dest return value correct for gz file"

    - name: Verify dest is returned correctly for bz2 file
      ansible.builtin.assert:
        that:
          - result_bz2.dest is defined
          - result_bz2.dest == "/tmp/test2-uncompressed.txt"
        fail_msg: "dest return value not correct for bz2 file"
        success_msg: "dest return value correct for bz2 file"

    - name: Check if cheat binary exists
      ansible.builtin.stat:
        path: /tmp/cheat
      register: cheat_binary
      failed_when: not cheat_binary.stat.exists

    - name: Verify cheat binary is executable
      ansible.builtin.stat:
        path: /tmp/cheat
      register: cheat_exec
      failed_when: not cheat_exec.stat.executable

    - name: Check if test-uncompressed.txt exists
      ansible.builtin.stat:
        path: /tmp/test-uncompressed.txt
      register: test_gz
      failed_when: not test_gz.stat.exists

    - name: Verify test-uncompressed.txt content
      ansible.builtin.command: cat /tmp/test-uncompressed.txt
      register: gz_content
      changed_when: false
      failed_when: "'test content for gz' not in gz_content.stdout"

    - name: Check if test2-uncompressed.txt exists
      ansible.builtin.stat:
        path: /tmp/test2-uncompressed.txt
      register: test_bz2
      failed_when: not test_bz2.stat.exists

    - name: Verify test2-uncompressed.txt content
      ansible.builtin.command: cat /tmp/test2-uncompressed.txt
      register: bz2_content
      changed_when: false
      failed_when: "'test content for bz2' not in bz2_content.stdout"

    - name: Verify dest is returned correctly for gz file to directory
      ansible.builtin.assert:
        that:
          - result_gz_dir.dest is defined
          - result_gz_dir.dest == "/tmp/uncompress-test-dir/test3.txt"
        fail_msg: "dest return value not correct for gz directory test"
        success_msg: "dest return value correct for gz directory test"

    - name: Verify dest is returned correctly for bz2 file to directory
      ansible.builtin.assert:
        that:
          - result_bz2_dir.dest is defined
          - result_bz2_dir.dest == "/tmp/uncompress-test-dir/test4.txt"
        fail_msg: "dest return value not correct for bz2 directory test"
        success_msg: "dest return value correct for bz2 directory test"

    - name: Verify dest is returned correctly for tar.gz file to directory
      ansible.builtin.assert:
        that:
          - result_tar_gz_dir.dest is defined
          - result_tar_gz_dir.dest == "/tmp/uncompress-test-dir/test5.tar"
        fail_msg: "dest return value not correct for tar.gz directory test (should be .tar)"
        success_msg: "dest return value correct for tar.gz directory test"

    - name: Check if test3.txt exists in directory
      ansible.builtin.stat:
        path: /tmp/uncompress-test-dir/test3.txt
      register: test3_file
      failed_when: not test3_file.stat.exists

    - name: Verify test3.txt content
      ansible.builtin.command: cat /tmp/uncompress-test-dir/test3.txt
      register: test3_content
      changed_when: false
      failed_when: "'test content for gz directory' not in test3_content.stdout"

    - name: Check if test4.txt exists in directory
      ansible.builtin.stat:
        path: /tmp/uncompress-test-dir/test4.txt
      register: test4_file
      failed_when: not test4_file.stat.exists

    - name: Verify test4.txt content
      ansible.builtin.command: cat /tmp/uncompress-test-dir/test4.txt
      register: test4_content
      changed_when: false
      failed_when: "'test content for bz2 directory' not in test4_content.stdout"

    - name: Check if test5.tar exists in directory (stripped from .tar.gz)
      ansible.builtin.stat:
        path: /tmp/uncompress-test-dir/test5.tar
      register: test5_file
      failed_when: not test5_file.stat.exists

    - name: Display verification results
      ansible.builtin.debug:
        msg: "All uncompress operations verified successfully!"
