---
dependency:
  name: shell
  command: echo "No dependencies needed"
driver:
  name: default
platforms:
  - name: instance
    groups:
      - testgroup
provisioner:
  name: ansible
  config_options:
    defaults:
      allow_broken_conditionals: true
  inventory:
    host_vars:
      instance:
        ansible_connection: local
verifier:
  name: ansible
